// Generated by https://quicktype.io

import 'dart:convert';

VanModel vanModelFromJson(String str) => VanModel.fromJson(json.decode(str));

String vanModelToJson(VanModel data) => json.encode(data.toJson());

class VanModel {
  VanModel({
    this.drivername,
    this.number,
    this.model,
    this.phone,
  });

  String drivername;
  String number;
  String model;
  String phone;

  factory VanModel.fromJson(Map<String, dynamic> json) => VanModel(
        drivername: json["DRIVERNAME"] == null ? null : json["DRIVERNAME"],
        number: json["NUMBER"] == null ? null : json["NUMBER"],
        model: json["MODEL"] == null ? null : json["MODEL"],
        phone: json["PHONE"] == null ? null : json["PHONE"],
      );

  Map<String, dynamic> toJson() => {
        "DRIVERNAME": drivername == null ? null : drivername,
        "NUMBER": number == null ? null : number,
        "MODEL": model == null ? null : model,
        "PHONE": phone == null ? null : phone,
      };
}
